### ISSUE TITLE
Generate gs://openteams-score/pypi.parquet

### ISSUE THREAD

**Issue by srossross** [openteamsinc/opensourcescore.dev#1]
This should scrape pypi and collect info into a parquet file

Acceptance criteria

- [x] Create the Parquet file
- [x] Create pull request for code

**Comment by srossross** [comment]
Upload the data to [openteams-score-data](https://console.cloud.google.com/storage/browser/openteams-score-data?authuser=2&project=openteams-score)

**Comment by karamba228** [comment]
PR #17 should cover the second half of this ticket
