### ISSUE TITLE
Generate security vulnerability dataset

### ISSUE THREAD

**Issue by srossross** [openteamsinc/opensourcescore.dev#14]
1. identify an open source vulnerability database
2. Scrape a vulnerability database for all the info needed in the [research](https://github.com/openteamsinc/Score/issues?q=is%3Aissue+is%3Aopen+label%3Aresearch) phase

The dataset output format and location should be documented

This should be a new command like `python -m score.cli vulnerabilities`

**Comment by siddheshghadi751** [comment]
**National Vulnerability Database (NVD)**

URL: [https://nvd.nist.gov/](vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)

**CVE Details**

URL: [https://www.cvedetails.com/](vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)

**OSV (Open Source Vulnerabilities)**

URL: [https://osv.dev/](vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)

**VulnDB**

URL: [https://vulndb.cyberriskanalytics.com/](vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)

**GitHub Security Advisories**

URL: [https://github.com/advisories](vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)

**Snyk Vulnerability Database**

URL: [https://snyk.io/vuln](vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)

**Comment by siddheshghadi751** [comment]
The JSON response from the OSV API contains detailed information about vulnerabilities. 

### JSON Structure

```json
{
  "vulns": [
    {
      "id": "OSV-2020-744",
      "summary": "Heap-double-free in mrb_default_allocf",
      "details": "OSS-Fuzz report: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23801\n\n```\nCrash type: Heap-double-free\nCrash state:\nmrb_default_allocf\nmrb_free\nobj_free\n```\n",
      "modified": "2022-04-13T03:04:39.780694Z",
      "published": "2020-07-04T00:00:01.948828Z",
      "references": [
        {
          "type": "REPORT",
          "url": "https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23801"
        }
      ],
      "affected": [
        {
          "package": {
            "name": "mruby",
            "ecosystem": "OSS-Fuzz",
            "purl": "pkg:generic/mruby"
          },
          "ranges": [
            {
              "type": "GIT",
              "repo": "https://github.com/mruby/mruby",
              "events": [
                {
                  "introduced": "9cdf439db52b66447b4e37c61179d54fad6c8f33"
                },
                {
                  "fixed": "97319697c8f9f6ff27b32589947e1918e3015503"
                }
              ]
            }
          ],
          "versions": [
            "2.1.2",
            "2.1.2-rc",
            "2.1.2-rc2"
          ],
          "ecosystem_specific": {
            "severity": "HIGH"
          },
          "database_specific": {
            "source": "https://github.com/google/oss-fuzz-vulns/blob/main/vulns/mruby/OSV-2020-744.yaml"
          }
        }
      ],
      "schema_version": "1.4.0"
    }
  ]
}
```

### Key Breakdown

- **`vulns`**: A list of vulnerabilities.
  - **`id`**: Unique identifier for the vulnerability (e.g., "OSV-2020-744").
  - **`summary`**: A brief summary of the vulnerability (e.g., "Heap-double-free in mrb_default_allocf").
  - **`details`**: Detailed description of the vulnerability, often including links to reports and crash states.
  - **`modified`**: Timestamp of the last modification (e.g., "2022-04-13T03:04:39.780694Z").
  - **`published`**: Timestamp of when the vulnerability was published (e.g., "2020-07-04T00:00:01.948828Z").
  - **`references`**: A list of references related to the vulnerability.
    - **`type`**: Type of reference (e.g., "REPORT").
    - **`url`**: URL to the reference (e.g., "https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23801").
  - **`affected`**: A list of affected packages and versions.
    - **`package`**: Information about the affected package.
      - **`name`**: Name of the package (e.g., "mruby").
      - **`ecosystem`**: Ecosystem of the package (e.g., "OSS-Fuzz").
      - **`purl`**: Package URL (e.g., "pkg:generic/mruby").
    - **`ranges`**: A list of version ranges affected by the vulnerability.
      - **`type`**: Type of version control (e.g., "GIT").
      - **`repo`**: Repository URL (e.g., "https://github.com/mruby/mruby").
      - **`events`**: Events marking the introduction and fixing of the vulnerability.
        - **`introduced`**: Commit hash where the vulnerability was introduced (e.g., "9cdf439db52b66447b4e37c61179d54fad6c8f33").
        - **`fixed`**: Commit hash where the vulnerability was fixed (e.g., "97319697c8f9f6ff27b32589947e1918e3015503").
    - **`versions`**: Specific versions affected by the vulnerability (e.g., "2.1.2", "2.1.2-rc", "2.1.2-rc2").
    - **`ecosystem_specific`**: Ecosystem-specific information.
      - **`severity`**: Severity of the vulnerability (e.g., "HIGH").
    - **`database_specific`**: Database-specific information.
      - **`source`**: Source URL for the vulnerability data (e.g., "https://github.com/google/oss-fuzz-vulns/blob/main/vulns/mruby/OSV-2020-744.yaml").
  - **`schema_version`**: Version of the schema used (e.g., "1.4.0").

This structure provides comprehensive information about each vulnerability, including its identification, description, affected packages and versions, and references to further details.

**Comment by siddheshghadi751** [comment]
https://google.github.io/osv.dev/data/#data-dumps

# Data dumps
For convenience, these sources are aggregated and [continuously](https://github.com/google/osv.dev/blob/master/deployment/clouddeploy/gke-workers/base/exporter.yaml) exported to a GCS bucket maintained by OSV: [gs://osv-vulnerabilities](https://storage.googleapis.com/osv-vulnerabilities/index.html)

This bucket contains individual entries of the format gs://osv-vulnerabilities/<ECOSYSTEM>/<ID>.json as well as a zip containing all vulnerabilities for each ecosystem at gs://osv-vulnerabilities/<ECOSYSTEM>/all.zip.

E.g. for PyPI vulnerabilities:

#### Or download over HTTP via https://osv-vulnerabilities.storage.googleapis.com/PyPI/all.zip
gsutil cp gs://osv-vulnerabilities/PyPI/all.zip .

Some ecosystems contain a : separator in the name (e.g. Alpine:v3.17). For these ecosystems, the data dump will always contain an ecosystem directory without the :.* suffix (e.g. Alpine). This will contain all the advisories of the ecosystem with the same prefix (e.g. All Alpine:.*).

A list of all current ecosystems is available at [gs://osv-vulnerabilities/ecosystems.txt](https://osv-vulnerabilities.storage.googleapis.com/ecosystems.txt)

**Comment by siddheshghadi751** [comment]
@srossross  PR #53  is related to this issue. 

Currently on OSV Database is scrapped looking for others too.

**Comment by siddheshghadi751** [comment]
For OSV parameters they have schema mentioned : https://ossf.github.io/osv-schema/ These are the values we get in JSON. Some are mentioned on top but others are in these file
