### ISSUE TITLE
Define Maturity/Developing: The project is actively being developed and shows promise for the future

### ISSUE THREAD

**Issue by srossross** [openteamsinc/opensourcescore.dev#3]
Define what this means and where we are going to source the data for this

this should be defined like a simple `if` statement like `if number_commits > 100 & project_age > 1year` 

### Acceptance criteria

Add this to a Document containing all the definitions

**Comment by karamba228** [comment]
```
(releases_in_last_year <= 2 and
        (monthly_downloads_pypi < 1000 or monthly_downloads_conda < 1000) and
        project_age < 1*365 and
        github_stars <= 50 and
        github_forks <= 10 and
        maintainer is not None and
        license is not None):
```

**Comment by srossross** [comment]
This package is developing if 

* Releases in the last year (pypi, conda) is less than 2
* Our combined monthly downloads is < 1000
* license is not None
* maintainer is not None (TODO: futher discussion is needed)

```
if Releases in the last year (pypi, conda) is less than 2:
   status = "Developing"
   notes.append(f"This is developing because ...")
* ```

Add a note to the `score_notes` on why this is in 'developing'

**Comment by siddheshghadi751** [comment]
For  maturity/developing:
The package is under active development. It has a growing user base, regular updates, and improving documentation.

### Parameters and Conditions for Maturity/Developing

#### 1. Age of the Package
- **First Release Date**: Between 1 and 3 years old.
- **Recent Release Date**: Regular updates within the last year.

#### 2. Release Frequency
- **Number of Releases**: Between 5 and 20 releases.
- **Release Interval**: Regular release intervals (e.g., every few months).

#### 3. Versioning
- **Current Version**: Stable versions (e.g., 1.x, 2.x) but not yet at a major milestone (e.g., 1.0.0).

#### 4. Development Status
- **Classifier**: Development status marked as "Beta" or "Production/Stable".

#### 5. Documentation
- **ReadMe File**: Present and of good quality.
- **Documentation Quality**: Comprehensive documentation available.

#### 6. Community and Support
- **Number of Contributors**: Between 3 and 10 contributors.
- **Issue Tracker Activity**: Balanced number of open and closed issues.

#### 7. Usage Metrics
- **Download Statistics**: Moderate number of downloads.
- **Dependent Projects**: Some dependent projects.

### Explanation:
- **Age Condition**: Checks if the first release date is between 1 and 3 years old.
- **Release Frequency Condition**: Checks if the number of releases is between 5 and 20.
- **Versioning Condition**: Checks if the current version is stable and not a pre-release.
- **Development Status Condition**: Checks if the development status is marked as "Beta" or "Stable".
- **Documentation Condition**: Checks if the README is present and of good quality.
- **Community Support Condition**: Checks if the number of contributors is between 3 and 10.
- **Issue Tracker Activity Condition**: Checks if the number of open issues is less than or equal to closed issues.
- **Usage Metrics Condition**: Checks if the number of downloads is moderate.
- **Dependent Projects Condition**: Checks if there are some dependent projects.
