### ISSUE TITLE
Define: Maturity/Experimental: The project is new, innovative, and in the early stages of development

### ISSUE THREAD

**Issue by srossross** [openteamsinc/opensourcescore.dev#4]
Define what this means and where we are going to source the data for this

this should be defined like a simple `if` statement like `if number_commits > 100 & project_age > 1year` 

This also should include where the information comes from.

**Comment by karamba228** [comment]
```
if (releases_in_last_year <= 2 and
        (monthly_downloads_pypi < 1000 or monthly_downloads_conda < 1000) and
        project_age < 1*365 and
        github_stars <= 50 and
        github_forks <= 10 and
        maintainer is not None and
        license is not None):
        return True
```

**Comment by srossross** [comment]
> monthly_downloads_pypi < 1000 and monthly_downloads_conda < 1000

what if this package is not hosted by conda?

**Comment by karamba228** [comment]
That should have been an OR statement, thank you for catching that

**Comment by siddheshghadi751** [comment]
Definition of Maturity/Experimental can be on these basis : 
The package is in early stages of development. It may have frequent breaking changes, limited documentation, and a small user base.

### Parameters and Conditions for Experimental Maturity

#### 1. Age of the Package
- **First Release Date**: Less than 1 year old.
- **Recent Release Date**: Frequent recent updates might indicate ongoing development.

#### 2. Release Frequency
- **Number of Releases**: Fewer than 5 releases.
- **Release Interval**: Irregular release intervals.

#### 3. Versioning
- **Current Version**: Pre-release versions (e.g., alpha, beta, RC).

#### 4. Development Status
- **Classifier**: Development status marked as "Alpha" or "Beta".

#### 5. Documentation
- **ReadMe File**: Absence or poor quality of README file.
- **Documentation Quality**: Lack of comprehensive documentation.

#### 6. Community and Support
- **Number of Contributors**: Fewer than 3 contributors.
- **Issue Tracker Activity**: High number of open issues relative to closed issues.

#### 7. Usage Metrics
- **Download Statistics**: Low number of downloads.
- **Dependent Projects**: Few or no dependent projects.

### Explanation:
- **Age Condition**: Checks if the first release date is less than 1 year old.
- **Release Frequency Condition**: Checks if the number of releases is fewer than 5.
- **Versioning Condition**: Checks if the current version is a pre-release (alpha, beta, RC).
- **Development Status Condition**: Checks if the development status is marked as "Alpha" or "Beta".
- **Documentation Condition**: Checks if the README is absent or of poor quality.
- **Community Support Condition**: Checks if the number of contributors is fewer than 3.
- **Issue Tracker Activity Condition**: Checks if the number of open issues is greater than closed issues.
- **Usage Metrics Condition**: Checks if the number of downloads is low.
- **Dependent Projects Condition**: Checks if there are few or no dependent projects.
