### ISSUE TITLE
Create Pypi Web Scraper

### ISSUE THREAD

**Issue by srossross** [openteamsinc/opensourcescore.dev#8]
and define the data that is needed to include

**Comment by karamba228** [comment]
### Data that will be web scraped from PyPi

* `name`: (Project name)
* `classifiers`: (A list of project classifiers)
* `bugtrack_url`: (same as project_urls.tracker, one or the other can be null)
* `docs_url`: (same as project_urls.documentation, one or the other can be null)
* `download_url`: (same as project_urls.download, one or the other can be null)
* `home_page`: (same as project_urls.homepage, one or the other can be null)
* `keywords`: (A string of keywords a project is related to)
* `maintainer`: (Maintainer name)
* `maintainer_email`: (Maintainer email)
- `project_urls`:
- * Documentation
- * Download
- * Homepage
- * Release notes
- * Source
- * Tracker
* `release_url`: (pypi url to the latest release of the package)
* `requires_python`: (range or python versions required)
* `version`: (Latest Version Number)
* `yanked_reason`: (Reason for the package version to be removed `null` in most cases)
