### ISSUE TITLE
Add License check to score

### ISSUE THREAD

**Issue by srossross** [openteamsinc/opensourcescore.dev#83]
(with less permissive license a person using the package for proprietary projects may run into legal issues therefore further investigation needed or "caution needed")
or if no license then "moderate risk"

**Comment by siddheshghadi751** [comment]
1. **GNU General Public License (GPL)**
2. **GNU Affero General Public License (AGPL)**
3. **GNU Lesser General Public License (LGPL)**
4. **Server Side Public License (SSPL)**
5. **Common Development and Distribution License (CDDL)**
6. **Mozilla Public License (MPL)**
7. **Eclipse Public License (EPL)**

These are common less permissive license. Do we need to add any other license? @srossross
