### ISSUE TITLE
Add Last update to score 

### ISSUE THREAD

**Issue by srossross** [openteamsinc/opensourcescore.dev#84]
For this do you think this is covered in `maturity: legacy` or should all `maturity: legacy` be 'caution needed'?

< 1. year "Healthy"
 1 -3 years "caution needed"
 3 -5 years "moderate risk"
>5 years then High Risk

**Comment by siddheshghadi751** [comment]
Yes,  all maturity: legacy should be categorized as "Caution Needed" if the latest commit is between 1 and 3 years old.
