### ISSUE TITLE
[SPIKE] Use the category definitions to create a concrete list of what data we need

### ISSUE THREAD

**Issue by srossross** [openteamsinc/opensourcescore.dev#9]
The result of this ticket should be the readme updated with the list of data sources and new tickets created to scrape those sources

**Comment by siddheshghadi751** [comment]
@srossross 
For all category definitions, I have already added in respective ticket.  #4 #5 #3 #6 #7   Some might need more better clarity but I need to create a table to compare all of this and decide the range of values we want to consider as per category. (For example : for downloads need to define how many downloads will make it consider as developing or experimental.)
